#!/usr/bin/env python3
"""Predator 8.026: finite exhaustive proof banking for prcom.

This is an enumeration experiment, not a first-proof search.

For a declared finite search space (strict pre-prcom assertion prefix, bounded
proof-search depth, bounded number of open goals, and an optional deterministic
per-goal candidate cap), enumerate every proof history in that space.  Distinct
proof histories are NOT quotiented by proof state.  A terminal child is checked
immediately; every distinct externally verified certificate is banked, and
search continues until the finite frontier is exhausted.

Scientific contract
-------------------
* V is a hard constraint: only independently Metamath-verified certificates
  enter the bank.
* H=0 is recorded for a closed verified certificate.
* H-prime is deliberately left unevaluated here: this enumerator does not claim
  a non-vacuous fractional-flow derivative merely because a terminal node is
  closed.  A future flow model may add that coordinate to these bank records.
* E is the number of nonterminal node expansions performed when the certificate
  is first generated by this exhaustive scheduler.
* Raw proof bits and a fully identified zlib level-9 telemetry length are
  recorded.  The latter is NOT claimed to be the final standardized l_K until
  the project freezes a codec/reference implementation specification.

Completeness is claimed ONLY if the frontier is naturally exhausted.  Safety
ceilings (--max-expanded/--max-frontier) cause an explicit INCOMPLETE result;
there is no silent pruning.

Candidate cap
-------------
--candidate-cap K deterministically keeps the K highest frozen-policy-scoring
assertion candidates for each selected open goal.  K=0 means every assertion-
head-compatible candidate in the strict pre-target prefix.  The cap is part of
the declared finite theorem/search space, not hidden pruning.

All open-goal choices are enumerated, so the search does not inherit pick_goal
as a completeness restriction.
"""
from __future__ import annotations

import argparse
from collections import deque
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import time
import zlib

import predator8_016_prcom_exactify as P
from predator8_ml_ranker import RuntimePolicy

B = P.B
ROOT = Path(__file__).resolve().parent
VERSION = "8.026-prcom-finite-exhaustive-bank"


def canonical_proof_bytes(proof) -> bytes:
    return (" ".join(proof)).encode("utf-8")


def proof_hash(proof) -> str:
    return hashlib.sha256(canonical_proof_bytes(proof)).hexdigest()


def make_certificate_text(statement, proof, environment_name: str, sha: str) -> str:
    return (
        "$( Predator %s exhaustive-bank candidate for prcom; proof_sha256=%s $)\n"
        % (VERSION, sha)
        + "$[ %s $]\n" % environment_name
        + "chk $p %s $= %s $.\n"
        % (" ".join(statement), " ".join(proof))
    )


def ranked_items(policy, gt, closers, openers, candidate_cap: int):
    items = list(closers) + list(openers)
    if candidate_cap <= 0 or len(items) <= candidate_cap:
        return items
    scores = policy.rank(gt, items)
    scored = list(zip(scores, items))
    # Larger policy score is better in the existing Predator controller.
    # Use theorem label as a deterministic secondary key.
    scored.sort(key=lambda p: (-float(p[0]), p[1][0]))
    return [item for _, item in scored[:candidate_cap]]


def enumerate_children(E, index, policy, node, max_open: int, candidate_cap: int):
    """Enumerate every legal open-goal choice and every declared candidate."""
    out = []
    for gi in range(len(node.goals)):
        gt, slot, hix = node.goals[gi]
        rest = node.goals[:gi] + node.goals[gi + 1:]
        gt = E.apply_sub(gt, node.sub)
        closers, openers = index.candidates(gt)
        items = ranked_items(policy, gt, closers, openers, candidate_cap)

        for lab, ct, data in items:
            m = {}
            c2 = E.rename_apart(ct, m)
            s2 = E.unify(c2, gt, node.sub)
            if s2 is None:
                continue
            _, f_hyps, e_hyps, _ = data
            fmap = {var: m.get(var, E.fresh(tc)) for _, tc, var in f_hyps}
            for _, tc, var in f_hyps:
                m.setdefault(var, fmap[var])
            step = E.Step(lab, fmap, data)
            newgoals = []
            ok = True
            for hj, (_, stat) in enumerate(e_hyps):
                try:
                    ht = E.G.parse(stat[1:], "wff", index.by_tc)
                except (RecursionError, E.MMError):
                    ht = None
                if ht is None:
                    ok = False
                    break
                newgoals.append((E.rename_apart(ht, m), step, hj))
            if not ok:
                continue

            successor_goals = newgoals + rest
            if len(successor_goals) > max_open:
                continue
            out.append(E.Node(
                successor_goals,
                s2,
                node.trail + ((slot, hix, step),),
                node.depth + 1,
            ))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("environment")
    ap.add_argument("--engine", default="Predator_8.001_FROZEN.py")
    ap.add_argument("--model", required=True)
    ap.add_argument("--label", default="prcom")
    ap.add_argument("--max-depth", type=int, default=4)
    ap.add_argument("--max-open", type=int, default=8)
    ap.add_argument("--candidate-cap", type=int, default=16,
                    help="per open goal; 0 means every compatible pre-target assertion")
    ap.add_argument("--max-expanded", type=int, default=250000,
                    help="safety ceiling; 0 means no expansion ceiling")
    ap.add_argument("--max-frontier", type=int, default=500000,
                    help="safety ceiling; 0 means no frontier ceiling")
    ap.add_argument("--progress", type=int, default=5000)
    ap.add_argument("--bank-dir", default="prcom_exhaustive_bank")
    ap.add_argument("--summary", default="prcom_exhaustive_bank_summary.json")
    args = ap.parse_args()

    if args.label != "prcom":
        ap.error("8.026 is intentionally scoped to prcom")
    if args.max_depth < 0 or args.max_open < 0 or args.candidate_cap < 0:
        ap.error("depth/open/candidate bounds must be nonnegative")

    environment = Path(args.environment).resolve()
    model = Path(args.model).resolve()
    engine_path = Path(args.engine).resolve()
    bank_dir = Path(args.bank_dir).resolve()
    bank_dir.mkdir(parents=True, exist_ok=True)
    bank_jsonl = bank_dir / "bank.jsonl"

    E = B.load_engine(engine_path)
    print("=" * 78)
    print("Predator %s -- prcom" % VERSION)
    print("=" * 78)
    print("DECLARED FINITE SPACE: depth<=%d open<=%d candidate_cap=%s all-open-goals=YES"
          % (args.max_depth, args.max_open,
             "ALL" if args.candidate_cap == 0 else args.candidate_cap))
    print("SAFETY CEILINGS: max_expanded=%s max_frontier=%s (ceiling hit => INCOMPLETE)"
          % ("NONE" if args.max_expanded == 0 else f"{args.max_expanded:,}",
             "NONE" if args.max_frontier == 0 else f"{args.max_frontier:,}"))
    print("NO proof-state quotient; NO frontier pruning; continue after every proof")

    mm = E.load(str(environment), say=print)
    cutoff = mm.order.index(args.label)
    by_tc = B.strict_prefix_grammar(E, mm, cutoff)
    index = E.Index(mm, by_tc, upto=cutoff, say=print)
    statement = mm.labels[args.label][1][3]
    target_data = mm.labels[args.label][1]
    goal = E.G.parse(statement[1:], "wff", by_tc)

    policy = RuntimePolicy.load(model, E, by_tc)
    md = policy.artifact["metadata"]
    if md.get("environment_sha256") != B.sha256(environment):
        raise SystemExit("model/environment hash mismatch")
    if md.get("cutoff_before") != args.label or md.get("target_proof_used") is not False \
            or md.get("downstream_used") is not False:
        raise SystemExit("model leakage/cutoff attestation failed")

    fvar, fallback = B.formal_variables(E, mm, cutoff)
    original_proofs = mm.proofs
    mm.proofs = B.GuardedProofs(original_proofs, args.label)

    # Reuse the same rigorous terminal checker semantics as 8.016.
    probe_ctx = P.ProbeContext(E, index, mm, target_data, fvar, fallback)

    frontier = deque([E.Node([(goal, None, 0)], {}, (), 0)])
    expanded = 0
    generated = 0
    terminal_candidates = 0
    duplicate_certificates = 0
    internally_rejected = 0
    externally_rejected = 0
    banked = []
    seen_proof_hashes = set()
    stop_reason = None
    started = time.perf_counter()

    def bank_terminal(node, found_after_expansions: int):
        nonlocal terminal_candidates, duplicate_certificates
        nonlocal internally_rejected, externally_rejected

        terminal_candidates += 1
        if not probe_ctx.closed_verifies(node):
            internally_rejected += 1
            print("[TERMINAL-REJECT] in-process Metamath rejected terminal history")
            return

        result = B.reconstruct(node)
        root, sub = result
        if root is None:
            internally_rejected += 1
            return
        proof = root.emit(sub, fvar, fallback)
        sha = proof_hash(proof)
        if sha in seen_proof_hashes:
            duplicate_certificates += 1
            return

        canonical = canonical_proof_bytes(proof)
        ordinal = len(banked) + 1
        cert_path = bank_dir / ("proof_%05d_%s.mm" % (ordinal, sha[:12]))
        cert_path.write_text(
            make_certificate_text(statement, proof, environment.name, sha),
            encoding="utf-8",
        )

        external = subprocess.run(
            [sys.executable, str(ROOT / "predator8_external_cv.py"),
             str(environment), "--target", args.label,
             "--certificate", str(cert_path)],
            cwd=str(ROOT), text=True, capture_output=True, check=False,
        )
        if external.returncode:
            externally_rejected += 1
            print("[PROTOCOL-FAIL] external verifier rejected %s" % sha)
            print((external.stdout + external.stderr).strip())
            return

        seen_proof_hashes.add(sha)
        record = {
            "theorem": args.label,
            "V": 1,
            "H": 0.0,
            "H_prime_abs": None,
            "H_prime_status": "not-evaluated-nonvacuously",
            "E_first_generated": int(found_after_expansions),
            "search_application_depth": int(node.depth),
            "proof_steps": int(len(proof)),
            "proof_sha256": sha,
            "raw_proof_bits": int(8 * len(canonical)),
            "zlib9_bits_telemetry": int(8 * len(zlib.compress(canonical, 9))),
            "zlib_runtime": zlib.ZLIB_VERSION,
            "certificate_file": cert_path.name,
            "candidate_cap": int(args.candidate_cap),
            "max_depth": int(args.max_depth),
            "max_open": int(args.max_open),
        }
        banked.append(record)
        with bank_jsonl.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record, sort_keys=True) + "\n")
        print("[BANKED] #%d E=%d depth=%d proof_steps=%d raw_bits=%d zlib9_bits=%d sha=%s"
              % (ordinal, found_after_expansions, node.depth, len(proof),
                 record["raw_proof_bits"], record["zlib9_bits_telemetry"], sha))

    try:
        while frontier:
            if args.max_expanded and expanded >= args.max_expanded:
                stop_reason = "max-expanded-ceiling"
                break
            if args.max_frontier and len(frontier) > args.max_frontier:
                stop_reason = "max-frontier-ceiling"
                break

            node = frontier.popleft()
            if not node.goals:
                # Normally terminal children are banked eagerly at generation,
                # but keep this branch for defensive completeness.
                bank_terminal(node, expanded)
                continue
            if node.depth >= args.max_depth or len(node.goals) > args.max_open:
                continue

            expanded += 1
            children = enumerate_children(
                E, index, policy, node, args.max_open, args.candidate_cap)
            generated += len(children)

            for child in children:
                if not child.goals:
                    # Eager terminal recognition: discovering a finished proof
                    # does not require a later artificial terminal-node pop.
                    bank_terminal(child, expanded)
                elif child.depth < args.max_depth:
                    frontier.append(child)
                # Nonterminal child at exactly max_depth is outside continuation
                # but is still part of the bounded tree boundary.

            if args.progress and expanded % args.progress == 0:
                print("[PROGRESS] expanded=%s generated=%s frontier=%s terminal=%s distinct_verified=%s elapsed=%.1fs"
                      % (f"{expanded:,}", f"{generated:,}", f"{len(frontier):,}",
                         f"{terminal_candidates:,}", f"{len(banked):,}",
                         time.perf_counter() - started))
    finally:
        mm.proofs = original_proofs

    elapsed = time.perf_counter() - started
    complete = stop_reason is None and not frontier

    best_E = min((r["E_first_generated"] for r in banked), default=None)
    best_steps = min((r["proof_steps"] for r in banked), default=None)
    best_raw = min((r["raw_proof_bits"] for r in banked), default=None)
    best_z = min((r["zlib9_bits_telemetry"] for r in banked), default=None)

    summary = {
        "version": VERSION,
        "theorem": args.label,
        "constraint": "V=1",
        "declared_space": {
            "strict_prefix_before_target": True,
            "all_open_goal_choices": True,
            "proof_histories_quotiented": False,
            "max_depth": args.max_depth,
            "max_open": args.max_open,
            "candidate_cap": args.candidate_cap,
        },
        "safety_ceilings": {
            "max_expanded": args.max_expanded,
            "max_frontier": args.max_frontier,
        },
        "complete_within_declared_space": complete,
        "stop_reason": "frontier-exhausted" if complete else stop_reason,
        "expanded_nonterminal_nodes": expanded,
        "generated_children": generated,
        "terminal_candidates": terminal_candidates,
        "distinct_verified_certificates": len(banked),
        "duplicate_certificates": duplicate_certificates,
        "internally_rejected_terminals": internally_rejected,
        "externally_rejected_certificates": externally_rejected,
        "best_known_objectives": {
            "H": 0.0 if banked else None,
            "H_prime_abs": None,
            "E_first_generated": best_E,
            "proof_steps_telemetry": best_steps,
            "raw_proof_bits": best_raw,
            "zlib9_bits_telemetry": best_z,
        },
        "elapsed_seconds": elapsed,
        "bank_file": str(bank_jsonl.name),
    }
    Path(args.summary).write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n",
                                  encoding="utf-8")

    print("=" * 78)
    print("FINITE EXHAUSTIVE BANK SUMMARY")
    print(json.dumps(summary, indent=2, sort_keys=True))
    if complete:
        print("OUTCOME: COMPLETE WITHIN DECLARED FINITE SPACE; all distinct verified certificates banked")
        return 0
    print("OUTCOME: INCOMPLETE ENUMERATION; safety ceiling reached, no completeness claim")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
